#Tiers
#   <id>:
#     Name: <name>
#     Block: <BlockName, no id>

Tiers:
  0:
    Name: "Tier 1"
    Block: DIAMOND_BLOCK

# Security names
Security:
  LOW: "&fLow"
  MEDIUM: "&dMEDIUM"
  HIGH: "&fHIGH"

Menu:
  CellItem: black_stained_glass_pane

